engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
  duplication:
    enabled: true
    config:
      languages:
      - "php"

ratings:
  paths:
  - "**.php"