engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 20
        javascript:
ratings:
  paths:
  - "**.php"