# .scrutinizer.yml

filter:
    excluded_paths: [vendor/*, doc/*, tests/*]

tools:
    php_cpd: true
    php_pdepend: true
    php_analyzer: true
    php_sim: true
    php_changetracking: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend:
        excluded_dirs: [vendor, doc, tests]

build:
    environment:
        php:
            version: 7.1
            ini:
                'date.timezone': 'Europe/Amsterdam'
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=tests/output/coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'